# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: Build of Universal Blue base image with Niri WM

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/errornointernet/packages/repo/fedora-%OS_VERSION%/errornointernet-packages-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      # WM
      - niri
      - xwayland-satellite
      - xdg-desktop-portal-hyprland
      - lxqt-policykit
      # qemu etc.
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - guestfs-tools
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
      - python3-tools
      - python3-libguestfs
    remove:
      - nano 
      - nano-default-editor
      - tmux
      - htop
      - nvtop
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.valvesoftware.Steam
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
